### ISSUE TITLE
Wrong project languages response

### ISSUE THREAD

**Issue by BunnyHolder** [onesky/api-documentation-platform#20]
Current response:
```bash
en - en - English
zh - zh-CN - Chinese Simplified
fr - fr - French
de - de - German
pt - pt-PT - Portuguese (Portugal)
ru - ru - Russian
nl - nl - Dutch
pl - pl - Polish
da - da - Danish
lv - lv-LV - Latvian (Latvia)
lt - lt-LT - Lithuanian (Lithuania)
et - et-EE - Estonian (Estonia)
es - es-ES - Spanish (Spain)
pt - pt - Portuguese
es - es - Spanish
it - it - Italian
bg - bg-BG - Bulgarian (Bulgaria)
bg - bg - Bulgarian
```

I don't have **bg - bg** and **es - es** ant **pt - pt** registered in website. It seems that they get registered automatically if I upload them. 

**Expected result**
Return registered languages in website only. If not registered drop an error.

**Comment by VLMH** [comment]
When you upload a file via API and specified a language that hasn't activated, the language will be enabled by OneSky system automatically. This is a short hand for some users that don't need to remember if the language is activated before uploading file.

In your case, you can disable the language at OneSky platform and the language should disappear in the response.

**Comment by BunnyHolder** [comment]
Yes, I know, but I can't make sure other developers wont upload language that is not enabled.  Anyway, is it possible to have strict mode?

**Comment by VLMH** [comment]
I am sorry that currently there's no strict mode to limit the use of languages. Since one locale code only match with one language at OneSky system. At the moment, please clarify the locale list for your developers.
