### ISSUE TITLE
Missing ISO-639-2 in project languages response

### ISSUE THREAD

**Issue by OO00O0O** [onesky/api-documentation-platform#21]
Missing ISO-639-2 in project languages response. 

http://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by VLMH** [comment]
May I know your use of ISO-639-2 standard? Is that the platform of your app or the app framework required the standard?

**Comment by BunnyHolder** [comment]
It's custom platform. If there are uses of ISO-639-1 there should be support for -2 too. It represent language better. -1 you can mix with country code for exp: Estonian: language code -1: et country code: ee. In other hand -2 standard: est

**Comment by VLMH** [comment]
Thanks for you advice. We primarily picked ISO-639-1 for our system as most system do. There are number of standards that is difficult to handle them well. Even for ISO-639-2, there are ISO-639-2T and ISO-639-2B.

We will further consider your situation and if there's anything we can do. Please let me know. Thanks!

**Comment by BunnyHolder** [comment]
Please look into CrowdIn solutions.

**Comment by VLMH** [comment]
Sure. We will reference to existing solution. Thanks for your information.
