### ISSUE TITLE
No support for compressed translation download

### ISSUE THREAD

**Issue by OO00O0O** [onesky/api-documentation-platform#22]
It would be nice, that it be possible to order zip file over API, and later download it when other API link returned URL for it. 

Exp:
/project/1234567/file/order?type=zip&include=...&exlude=... Response: FileOrderId: 654158
/project/1234567/file/orderStatus?id=654158 Response: Generating AND/OR Done, Link

**Comment by VLMH** [comment]
That's a good idea. We have some discussions on it and your suggestion will be included in the coming revamp. However, we cannot deliver it shortly since we have to think on the whole flow thoroughly. Thanks!
