### ISSUE TITLE
Bad PHP file export output

### ISSUE THREAD

**Issue by BunnyHolder** [onesky/api-documentation-platform#23]
I have uploaded output of var_export, because API does not understand $msg['bla'].

And it seems that it could not return normal output of array too. It does not escape ' symbol and returns array formed with ' symbol.

**Comment by VLMH** [comment]
I need your account (email), project ID and file name as well in order to check the problem. Would you mind send a ticket to support@oneskyapp.com? Looks like it is not API specific and doesn't matter whether you export from API or OneSky platform.

**Comment by BunnyHolder** [comment]
So did you fixed it? Is it won't fix? Maybe it's a problem on my end with import? I did not recived any emails too.

**Comment by VLMH** [comment]
I have replied to your ticket yesterday. Let me forward again to you. Please let me know if you still cannot receive email in few minutes.
