### ISSUE TITLE
Screenshot upload issue

### ISSUE THREAD

**Issue by QuadRatNewBy** [onesky/api-documentation-platform#31]
I'm having problem uploading screenshot via API. Everything works fine except one fact - one `Tag` is always missing for uploaded screenshot.

What I'm doing (everything done via API):
1. Creating project group (Creates fine)
2. Creating project (Also fine)
3. Uploading 2 `INI` files with similar keys, but different locales (all phrases are uploaded and parsed ok)
4. Uploading screenshot with tags referencing 4 keys from file(s) uploaded on step 3. (Only 3 keys appear to have screenshot attached).

What I've tried:
* Reordering tags inside screenshot object (`POST` request body) - in case missed one is first in the tag list - *Nothing*
* Renaming keys - in case that missing one is first alphabetically - *Nothing*
* Reordering strings in original files - in case first key from file is skipped - **Bingo!**

It appears that key from first file's line is never attaches to screenshot by tag.

Thanks in advance!

**Comment by QuadRatNewBy** [comment]
It seams that files uploaded in "UTF with BOM" encoding processed in unexpected way - BOM is nt removed from file and attached as part of first key. 
So for me this issue is resolved, but it c an affect some one else (whoever uses UTF-with-BOM encoding).

Consider closing.

**Comment by rubyluk** [comment]
The BOM issue is fixed. Case closed
