### ISSUE TITLE
Export translations

### ISSUE THREAD

**Issue by viktorvas19** [onesky/api-documentation-platform#34]
We have problems to export translations via php Library for One Sky APP API. We have same upload files in OneSkyApp in format **.xls**, but We export the string of this files the API print error **"File format (.xlsx (Microsoft Excel 2007)) is not downloadable through API"**.

How can we download via API all the strings of a project?

Thanks you

**Comment by rubyluk** [comment]
API supported format list is available [here](https://github.com/onesky/api-documentation-platform/blob/master/reference/format.md) 

I am happy to have conversation with you in customer support. 
Cheers!
