### ISSUE TITLE
.NET API wrapper

### ISSUE THREAD

**Issue by avonwyss** [onesky/api-documentation-platform#38]
We have created a .NET API wrapper.

It is available as nuget package and the source is here: https://github.com/siriusch/Sirius.OneSky

You can add it to the list of wrappers if you want to.

**Comment by QuadRatNewBy** [comment]
Just piggy-backing here - how about adding my wrapper as well? https://github.com/QuadRatNewBy/OneSky.CSharp
PS. I tried to add it myself about a year ago by creating pull request but it gone stale for couple of month so I decided to remove it.

**Comment by avonwyss** [comment]
Hi there @QuadRatNewBy ! Sure you may piggy-backing so that both are added to the list! :)

This is a bit off topic in this issue but I had a look at your API wrapper before implementing my own but dismissed it for different reasons. I just opened some of the issues I noticed when looking at your code; however one of the main features missing for me was the ability to perform requests asynchronously.

**Comment by QuadRatNewBy** [comment]
@avonwyss thanks for your comment and opened issues! I will definitely look into them.
As for asynchronous requests, I can swear that I implemented them back at the time. Maybe they got lost on my old PC. Anyway, it's another way of improving my wrapper, so thanks for pointing that out!

**Comment by rubyluk** [comment]
Hi both! You guys are awesome! Thank you for the contribution!
Both are added to the list to spread the love. 😉
