### ISSUE TITLE
Upload fails with { message: 'String file not found', code: 404 }

### ISSUE THREAD

**Issue by bezysoftware** [onesky/api-documentation-platform#50]
I cannot upload phrases using the API, I get this error
```
{ message: 'String file not found', code: 404 }
```
Here's what the url looks like: 
```
https://platform.api.onesky.io/1/projects/159815/files?api_key=...&timestamp=1559209817&dev_hash=...&is_keeping_all_strings=false&file_format=IOS_STRINGS&file=Localizable.strings
```

The file with this name and format exist in the web app

**Comment by ryan-dan-coleman** [comment]
Hi there, please open a support request by emailing support@oneskyapp.com with your organization name. We will investigate your case.

**Comment by bezysoftware** [comment]
It turned out to be bug in my code. Still, would be nice to have some more verbose response to understand what the server sees. 
If anyone is interested, this it the code I used for powershell:

```powershell
    $form = @{
        'is_keeping_all_strings' = 'false'
        'file_format' = 'IOS_STRINGS'
        'file' = Get-Item $file
    }

    $response = Invoke-RestMethod -uri $uri -Method Post -Form $form
```
 In particular notice the 'file' parameter
